### ISSUE TITLE
The `lint` phase in `.travis.yml` should be updated

### ISSUE THREAD

**Issue by ubajze** [nautobot/nautobot-plugin-data-validation-engine#10]
The following is the current configuration for the `lint` phase in `.travis.yml`:

```
    - stage: "lint"
      before_script:
        - "pip install --upgrade pip"
        - "pip install invoke poetry toml"
        - "poetry config virtualenvs.create false"
        - "poetry install --no-interaction"
        - "invoke build"
      script:
        - "invoke black"
        - "invoke bandit"
        # - "invoke pydocstyle"
        # - "invoke flake8"
        # - "invoke yamllint"
        # - "invoke pylint"
```

As you can see four commands are currently disabled. Make sure that these are executed without any errors and enable commands again.
